---
title: "EarthTemperature"
date: '2023-10-10'
output: 
  flexdashboard::flex_dashboard:
    theme: 
       version: 4
       bootswatch: sketchy
    orientation: rows
    vertical_layout: scroll
    social: menu
runtime: shiny
css: dashboard.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, echo = FALSE, message =FALSE)
library(flexdashboard)  
library(shiny)
library(sf)
library(tidyverse)
library(hrbrthemes)
library(rnaturalearth)
library(crul)
library(ggplot2)
library(gganimate)
library(animation)
library(lubridate)
library(cowplot)
library(emojifont)
library(tmap)
library(DT)
options(width=100)
tmap_options(check.and.fix = TRUE)
#下载并读入地图数据
world_map <- rnaturalearth::ne_download(scale=110,
                                        category="cultural",
                                        type="countries",
                                        load=TRUE,
                                        destdir=tempdir(),
                                        returnclass="sf") %>%
  select(SOVEREIGNT,SOV_A3,ADMIN,ADM0_A3,geometry)

#根据地表温度数据中的国家或地区名称对地图作调整
world_map[world_map$ADMIN=="Bosnia and Herzegovina",]$ADMIN <- "Bosnia And Herzegovina"
world_map[world_map$ADMIN=="Falkland Islands",]$ADMIN <- "Falkland Islands(Islas Malvinas)"
world_map[world_map$ADMIN=="French Southern and Antarctic Lands",]$ADMIN <- "French Southern And Antarctic Lands"
world_map[world_map$ADMIN=="Guinea-Bissau",]$ADMIN <- "Guinea Bissau"	
world_map[world_map$ADMIN=="Palestine",]$ADMIN <- "Palestina"
world_map[world_map$ADMIN=="Republic of Serbia",]$ADMIN <- "Serbia"
world_map[world_map$ADMIN=="Republic of Congo",]$ADMIN <- "Congo"
world_map[world_map$ADMIN=="The Bahamas",]$ADMIN <- "Bahamas"	
world_map[world_map$ADMIN=="Trinidad and Tobago",]$ADMIN <- "Trinidad And Tobago"	
world_map[world_map$ADMIN=="United States of America",]$ADMIN <- "United States"	
world_map[world_map$ADMIN=="United Republic of Tanzania",]$ADMIN <- "Tanzania"

country <- read_csv("data/GlobalLandTemperaturesByCountry.csv")
state <- read_csv("data/GlobalLandTemperaturesByState.csv")
AUS <- read_sf("map/gadm41_AUS_shp/AUS_1/gadm41_AUS_1.shp") 
BRA <- read_sf("map/gadm41_BRA_shp/BRA_1/gadm41_BRA_1.shp")
CAN <- read_sf("map/gadm41_CAN_shp/CAN_1/gadm41_CAN_1.shp")
CHN <- read_sf("map/gadm41_CHN_shp/CHN_1/gadm41_CHN_1.shp")
IND <- read_sf("map/gadm41_IND_shp/IND_1/gadm41_IND_1.shp")
RUS <- read_sf("map/gadm41_RUS_shp/RUS_1/gadm41_RUS_1.shp")
USA <- read_sf("map/gadm41_USA_shp/USA_1/gadm41_USA_1.shp")

#设置"Country"所需的向量
cou_abbr_name <- c("global", "AUS", "BRA", "CAN", "CHN", "IND", "RUS", "USA")
cou_full_name <- c("global", "Australia", "Brazil", "Canada", "China",
                   "India", "Russia" ,"United States")

#设置日期输入
month_standard <- reactive({str_sub(input$time, 1, 7) %>% 
    paste("-01", sep = "")})
month_standard_country <- reactive({str_sub(input$time_country, 1, 7) %>% 
    paste("-01", sep = "")})

```

Global
=======================================================================

Sidebar {.sidebar}
-----------------------------------------------------------------------
Please choose time below:

```{r input}
#输入日期
dateInput("time", 
          strong("time:"),
          value = "2000-01-01",
          format = "yyyy-mm",
          min = "1743-11-01",
          max = "2013-09-01",
          startview = "decade",
          weekstart = 0,
          datesdisabled = paste(rep(paste(rep(1743:2013,each=12),"-",1:12, sep=""),each=30),"-",2:31,sep = "")
          )
```
Row
-----------------------------------------------------------------------
### Map

```{r map_render}
#绘制世界地表温度月度图
renderPlot({
  
  world_map %>% 
    left_join(filter(country, dt==month_standard()), 
              by = c("ADMIN" = "Country")) %>%
      ggplot(aes(frame=dt)) +
      geom_sf(aes(fill=AverageTemperature,geometry=geometry), colour = "white", size = 0.3) +
      scale_x_continuous(breaks = seq(-180, 180, 45), 
                        labels = function(x){paste0(x, "°")}) +
      scale_y_continuous(breaks = seq(-60, 90, 30), 
                        labels = function(x){paste0(x, "°")}) +
      scale_fill_gradient2(low = "#619ac3", mid = "#ede3e7", high="#c45a65") +
      labs(title="Average Temperature of every country", 
           caption = "Missing data from Antarctica",
           y="Latitude", x="Longitude")
  })
```

Row {data-height=150}
-----------------------------------------------------------------------
### Average Temperature

```{r valuebox_global_ave}
global_na <- reactive({na.omit(filter(country, dt==month_standard()))})

#展示该月全球平均地表温度
renderValueBox({
  valueBox(value = round(mean(global_na()$AverageTemperature),3),
           icon = "fas fa-thermometer-half",
           caption = "Global Average Temperature",
           color = "#fffefa")
})
```

### Highest Temperature

```{r valuebox_global_high}
#展示该月全球最高地表温度及其相对应国家
renderValueBox({

  tmax <- max(global_na()$AverageTemperature)
  valueBox(value = tmax,
           caption = paste("Highest country:",
                        global_na()[global_na()$AverageTemperature==tmax,][1,4]),
           icon = "fas fa-thermometer-full",
           color = "#f2e7e5")
})
```

### Lowest Temperature

```{r valuebox_global_low}
#展示该月全球最低地表温度及其相对应国家
renderValueBox({

  tmin <- min(global_na()$AverageTemperature)
  valueBox(value = tmin,
           caption = paste("Lowest country:",
                        global_na()[global_na()$AverageTemperature==tmin,][1,4]),
           icon = "fas fa-thermometer-empty",
           color = "#eef7f2")
})
```

Row 
-----------------------------------------------------------------------
### DataTable

```{r data_table}
#展示该月全球地表温度表格数据
DT::renderDataTable({
  DT::datatable(filter(country, dt==month_standard()))
})
```

Country
=======================================================================

Sidebar {.sidebar}
-----------------------------------------------------------------------

Please choose a country below:

```{r input_country}
#输入国家或地区
selectInput("region_country", 
            strong("Country:"),
            choices = c("Australia" = 2,
                        "Brazil" = 3,
                        "Canada" = 4,
                        "China Mainland" = 5,
                        "India" = 6,
                        "Russia" = 7,
                        "United States" = 8),
            selected = "Island")

#输入日期
dateInput("time_country", 
          strong("Month:"),
          value = "2000-01-01",
          format = "yyyy-mm",
          min = "1743-11-01",
          max = "2013-09-01",
          startview = "decade",
          weekstart = 0,)
```

Row {data-height=450}
-----------------------------------------------------------------------
### Map

```{r map_country}
#绘制国家或地区带有一级行政划分的地表温度月度图
renderPlot({
  shape <- merge(get(cou_abbr_name[as.numeric(input$region_country)]) ,
      filter(state, 
                Country==cou_full_name[as.numeric(input$region_country)],
                dt==month_standard_country()),
      by.x="NAME_1", 
      by.y="State")
tmap_mode("plot")
qtm(shape,fill = "AverageTemperature")
})
```
Row {data-height=150}
-----------------------------------------------------------------------
### Average Temperature

```{r valuebox_state_ave}
#数据处理-删去含缺失值的观测
state_na <- reactive({na.omit(filter(state, 
                         Country==cou_full_name[as.numeric(input$region_country)],
                         dt==month_standard_country()))})

#展示该月该国家或地区平均地表温度
renderValueBox({

  valueBox(value = round(country[country$Country==cou_full_name[as.numeric(input$region_country)]&country$dt==month_standard_country(),][1,2],3),
           caption = paste("Average Temperature in", 
                           cou_full_name[as.numeric(input$region_country)]),
           icon = "fas fa-thermometer-half",
           color = "#fffefa")
})
```

### Highest Temperature

```{r valuebox_state_high}
#展示该月该国家或地区最高地表温度
renderValueBox({
  m <- max(state_na()$AverageTemperature)
  valueBox(value = m,
           caption = paste("Highest state in", 
                           cou_full_name[as.numeric(input$region_country)], ":",
                          state_na()[state_na()$AverageTemperature==m,][1,4]),
           icon="fa fa-fire",
           color = "#f2e7e5")
})
```

### Lowest Temperature

```{r valuebox_state_low}
#展示该月该国家或地区最低地表温度
renderValueBox({
  m <- min(state_na()$AverageTemperature)
  valueBox(value = m,
           caption = paste("Lowest state in", 
                           cou_full_name[as.numeric(input$region_country)], ":",
                          state_na()[state_na()$AverageTemperature==m,][1,4]),
          icon="fa fa-snowflake-o",
           color = "#eef7f2")
})
```

Row
-----------------------------------------------------------------------
### Changing Tendency

```{r tendency_country}
renderPlot({
  Temp <- filter(country, 
                 Country==cou_full_name[as.numeric(input$region_country)])
  
  #绘制该国家历年7月与12月的地表温度变化折线图
  a <- ggplot(Temp[str_detect(Temp$dt, "^.....12"),], aes(x = dt)) + 
    geom_ribbon(aes(ymin = AverageTemperature-AverageTemperatureUncertainty,
                    ymax = AverageTemperature+AverageTemperatureUncertainty),
                color="white", fill="grey") +
    geom_line(aes(y =  AverageTemperature)) +
    geom_smooth(aes(y =  AverageTemperature), size = 0.8, color = "#619ac3") +
  
    geom_ribbon(data = Temp[str_detect(Temp$dt, "^.....07"),],
                aes(ymin = AverageTemperature-AverageTemperatureUncertainty,
                    ymax = AverageTemperature+AverageTemperatureUncertainty),
                color="white", fill="grey") +
    geom_line(data = Temp[str_detect(Temp$dt, "^.....07"),],
              aes(y =  AverageTemperature)) +
    geom_smooth(data = Temp[str_detect(Temp$dt, "^.....07"),],
                aes(y =  AverageTemperature), size = 0.8, color = "#f2e7e5") +
    xlab("Year") +
    ylab("Temperature") +
    geom_vline(xintercept = input$time_country, color = "#c45a65") +
    labs(title =paste("Average Temperature of", 
                      cou_full_name[as.numeric(input$region_country)],
                      "in every July and January"))
  
  #绘制该国家或地区该年每月的平均地表温度折线图
  b <- Temp %>%
    group_by(month(dt)) %>%
    summarise(ave = mean(AverageTemperature, na.rm=TRUE)) %>%
    ggplot(aes(x = `month(dt)`,y = ave)) +
    geom_line(color = "#83a78d", size = 1) +
    geom_point(color = "#74759b") +
    geom_vline(xintercept = month(month_standard_country()), color = "#c45a65") +
    geom_hline(yintercept = unlist(Temp[Temp$dt==month_standard_country(),][1,2]), 
               color = "#c45a65") +
    scale_x_continuous(breaks = 1:12) +
    labs(title = paste("Average Temperature of", 
                      cou_full_name[as.numeric(input$region_country)],
                      "in every month")) +
    xlab("Month") +
    ylab("Temperature")
  
  plot_grid(a,b,nrow=1)
})
```

Row
-----------------------------------------------------------------------
### DataTable

```{r datatable_country}
#展示该国家地表温度表格数据
DT::renderDataTable({
  DT::datatable(
    filter(state, 
           Country==cou_full_name[as.numeric(input$region_country)],
           dt==month_standard_country()) %>%
      select(dt, Country, State, AverageTemperature, 
             AverageTemperatureUncertainty)
    )
})
```


